import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Header from "./_components/Header";
import "@/sass/main.scss";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: LayoutProps<"/[locale]">) {
  const messages = await getMessages();
  return (
    <NextIntlClientProvider messages={messages}>
      <html
        lang="en"

        suppressHydrationWarning
      >
        <body className="min-h-screen flex flex-col justify-between ">
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
